### ISSUE TITLE
drupal/core 8.8.6 requires ext-dom

### ISSUE THREAD

**Issue by dhop90** [geerlingguy/drupal-container#26]
Trying to setup raspberry-pi-dramble on 4 rpi 4s.  I have been successful in Provisioning the Pis up to the point where the drupal nodes get configured.  The two drupal nodes are in "CrashLoopBackOff" status.

pi@kube1:~ $ kubectl get pods -A
NAMESPACE     NAME                                     READY   STATUS             RESTARTS   AGE
default       nfs-client-provisioner-7b57746cd-pg2n8   1/1     Running            3          27h
drupal        drupal-54856bf894-rxckw                  0/1     CrashLoopBackOff   19         79m
drupal        drupal-54856bf894-vnxxc                  0/1     CrashLoopBackOff   19         79m
drupal        mysql-8bbdcb879-vbq8m                    1/1     Running            3          27h
kube-system   coredns-5c98db65d4-jbmhn                 1/1     Running            4          45h
kube-system   coredns-5c98db65d4-tkds6                 1/1     Running            5          45h
kube-system   etcd-kube1                               1/1     Running            4          45h
kube-system   kube-apiserver-kube1                     1/1     Running            4          45h
kube-system   kube-controller-manager-kube1            1/1     Running            4          45h
kube-system   kube-flannel-ds-arm-4rh25                1/1     Running            5          45h
kube-system   kube-flannel-ds-arm-777ks                1/1     Running            5          45h
kube-system   kube-flannel-ds-arm-qn6rc                1/1     Running            2          27h
kube-system   kube-flannel-ds-arm-tvhwj                1/1     Running            5          45h
kube-system   kube-proxy-8dtck                         1/1     Running            4          45h
kube-system   kube-proxy-ksk4d                         1/1     Running            4          45h
kube-system   kube-proxy-wc8sx                         1/1     Running            2          27h
kube-system   kube-proxy-z72b6                         1/1     Running            4          45h
kube-system   kube-scheduler-kube1                     1/1     Running            4          45h
kube-system   metrics-server-f948cd54-wkzdk            1/1     Running            4          45h
kube-system   traefik-ingress-controller-6zzzn         1/1     Running            3          27h
kube-system   traefik-ingress-controller-pxhd2         1/1     Running            2          27h
kube-system   traefik-ingress-controller-z82vm         1/1     Running            3          27h
registry      docker-registry-7c68c86677-8rfcb         1/1     Running            3          27h

The problem seems to be with drupal/core 8.8.6 requiring ext-dom per the logs:

kubectl logs --follow pods/drupal-54856bf894-vnxxc -n drupal
Removing any existing files inside /var/www/html...
Downloading Drupal...
Download complete!
Configuring settings.php with environment variables...
Correcting permissions on /var/www...
Running composer install...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drupal/core 8.8.6 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - drupal/core 8.8.6 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - Installation request for drupal/core 8.8.6 -> satisfiable by drupal/core[8.8.6].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.4/cli/php.ini
    - /etc/php/7.4/cli/conf.d/10-opcache.ini
    - /etc/php/7.4/cli/conf.d/10-pdo.ini
    - /etc/php/7.4/cli/conf.d/20-apcu.ini
    - /etc/php/7.4/cli/conf.d/20-calendar.ini
    - /etc/php/7.4/cli/conf.d/20-ctype.ini
    - /etc/php/7.4/cli/conf.d/20-exif.ini
    - /etc/php/7.4/cli/conf.d/20-ffi.ini
    - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.4/cli/conf.d/20-ftp.ini
    - /etc/php/7.4/cli/conf.d/20-gettext.ini
    - /etc/php/7.4/cli/conf.d/20-iconv.ini
    - /etc/php/7.4/cli/conf.d/20-json.ini
    - /etc/php/7.4/cli/conf.d/20-phar.ini
    - /etc/php/7.4/cli/conf.d/20-posix.ini
    - /etc/php/7.4/cli/conf.d/20-readline.ini
    - /etc/php/7.4/cli/conf.d/20-shmop.ini
    - /etc/php/7.4/cli/conf.d/20-sockets.ini
    - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Could this be related to https://github.com/geerlingguy/drupal-vm/issues/1962 ? If so any ideas on how to fix?

Thanks

**Comment by geerlingguy** [comment]
I think I may have broken the images just a couple days ago—they should be using PHP 7.3 but are using a non-complete installation of PHP 7.4 instead, and that's causing these errors :(

I am getting something similar today:

```
 [preflight] Class DOMDocument does not exist
 [warning] Drush command terminated abnormally.
```

I am in the process of updating the images to use PHP 7.4 and I _believe_ this should fix things... sorry about the problem!

**Comment by dhop90** [comment]
No worries.  Thanks for the reply.  Please let me know when I should give it a try.

**Comment by geerlingguy** [comment]
@dhop90 - I believe it should be working now. Sorry about that!

**Comment by dhop90** [comment]
I tried the updated images, but getting similar results.

It's looking for drupal/core 8.9.0 now instead for core 8.8.6

I reran the main.yml ansible-playbook.  Is that the best way to pickup the new image?

pi@kube1:~ $ k logs -n drupal drupal-54856bf894-k9xbh
Removing any existing files inside /var/www/html...
Downloading Drupal...
Download complete!
Configuring settings.php with environment variables...
Correcting permissions on /var/www...
Running composer install...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drupal/core 8.9.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - drupal/core 8.9.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - Installation request for drupal/core 8.9.0 -> satisfiable by drupal/core[8.9.0].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.4/cli/php.ini
    - /etc/php/7.4/cli/conf.d/10-opcache.ini
    - /etc/php/7.4/cli/conf.d/10-pdo.ini
    - /etc/php/7.4/cli/conf.d/20-apcu.ini
    - /etc/php/7.4/cli/conf.d/20-calendar.ini
    - /etc/php/7.4/cli/conf.d/20-ctype.ini
    - /etc/php/7.4/cli/conf.d/20-exif.ini
    - /etc/php/7.4/cli/conf.d/20-ffi.ini
    - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.4/cli/conf.d/20-ftp.ini
    - /etc/php/7.4/cli/conf.d/20-gettext.ini
    - /etc/php/7.4/cli/conf.d/20-iconv.ini
    - /etc/php/7.4/cli/conf.d/20-json.ini
    - /etc/php/7.4/cli/conf.d/20-phar.ini
    - /etc/php/7.4/cli/conf.d/20-posix.ini
    - /etc/php/7.4/cli/conf.d/20-readline.ini
    - /etc/php/7.4/cli/conf.d/20-shmop.ini
    - /etc/php/7.4/cli/conf.d/20-sockets.ini
    - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by geerlingguy** [comment]
@dhop90 - You may need to go onto that server and (after you've stopped/killed/removed any containers that used this image) run `docker rmi [image name or hash here]` to make sure it's removed. Then it will be re-downloaded and the latest version used next time.
