### ISSUE TITLE
Can you please check this project ?

### ISSUE THREAD

**Issue by ankitjain28may** [geerlingguy/drupal-container#4]
Hello @geerlingguy, I am working on a similar project during this Google Summer of Code community bonding period so that developers can easily test and review the project and it will easy for developers and users to deploy their Drupal site to any server through SSH using Ansible. 
Link to the repo - https://github.com/dbjpanda/drupal-devops

**Comment by geerlingguy** [comment]
@ankitjain28may - Looks interesting! Definitely a project that is working to be very comprehensive in setting up and managing a Drupal 8 site. Looks like a good use of roles to split up the work and reuse Ansible code, though the project organization is a little confusing at first glance (there's mention of Docker, Ansible, AWS, DigitalOcean, etc.).

**Comment by ankitjain28may** [comment]
@geerlingguy thanks a lot, Is there any way that this project can help you and other drupal developers? I really want developers to use this project and i can work on it for making it better and i need your guidance.

**Comment by ankitjain28may** [comment]
Its readme is not organized and completed as that project is actually a fork of this project. Have a look over this project - https://github.com/ankitjain28may/drupal-best-practices
