### ISSUE TITLE
Issue with docker build due to End of life debian support

### ISSUE THREAD

**Issue by mah-sanjay** [geerlingguy/drupal-container#40]
During docker build, we encountered this issue:

```
> [main stage-1 17/20] RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y     libgmp-dev     php8.1-gmp:
0.351 Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
0.419 Get:2 http://deb.debian.org/debian-security buster/updates InRelease [34.8 kB]
0.442 Get:4 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
1.225 Get:3 https://packages.sury.org/php buster InRelease
1.297 Err:3 https://packages.sury.org/php buster InRelease
1.297   Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
1.448 Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7909 kB]
2.496 Get:6 http://deb.debian.org/debian-security buster/updates/main amd64 Packages [610 kB]
3.534 Get:7 http://deb.debian.org/debian buster-updates/main amd64 Packages [8788 B]
3.566 Reading package lists...
4.032 E: Failed to fetch https://packages.sury.org/php/dists/buster/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
4.032 E: The repository 'https://packages.sury.org/php buster InRelease' is not signed.
------
failed to solve: process "/bin/sh -c apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y     libgmp-dev     php${PHP_VERSION}-gmp" did not complete successfully: exit code: 100
```

Issue is caused by end of life debian support - https://github.com/oerdnj/deb.sury.org/issues/2098 

Thank you

**Comment by geerlingguy** [comment]
To fix this, I'll first need to update the php-apache-container build: https://github.com/geerlingguy/php-apache-container — I need to go from `buster` to probably `bookworm`: https://github.com/geerlingguy/php-apache-container/blob/master/main.yml#L7

**Comment by geerlingguy** [comment]
Step one is complete—I've rebuilt the base container on Bookworm. I'll update this repo to pull from it maybe on PHP 8.2 and see how it fares.

**Comment by geerlingguy** [comment]
This should be fixed as of commit https://github.com/geerlingguy/drupal-container/commit/7ebb8eeddbed7625f7daaa0e296b085a771f9506 — let me know if you have any trouble!

**Comment by mah-sanjay** [comment]
Hi @geerlingguy ,

Thanks alot for your quick response and resolving the issue immediately. 
I can confirm that the issue is resolved just by pulling latest image. Also adding the note that php version is now bumped to 8.2.

Much appreciate your work.

Sanjay
